### ISSUE TITLE
Add http proxy support for networks where people can only connect to internet via http proxy

### ISSUE THREAD

**Issue by timogoosen** [coolacid/logstash-filter-virustotal#4]
Not sure if you want to add this to the code or just want to document it but if somebody is on a network where they need to connect via http proxy in order to connect to the internet then they can just change the code in virustotal.rb to 

<pre>
    connection = Faraday.new(baseurl, ssl: {verify:false}) do |connection|
      # middleware ...
      connection.adapter :em_http

      connection.proxy "http://172.20.1.2:8080"

</pre>

Or if they are making use of an HTTP proxy that requires authentication then change the code in virustotal.rb to:

<pre>
    connection = Faraday.new(baseurl, ssl: {verify:false}) do |connection|
      # middleware ...
      connection.adapter :em_http

      connection.proxy "http://username:somep3assword@172.20.1.2:8080"

</pre>

**Comment by coolacid** [comment]
Not going to add this - nice work around, however most proxies can whitelist an IP address and this is how it should probably be done.
